### PR TITLE
Jinke

### PR DESCRIPTION
**Pull request by jink-e**
implement getAudioTime() and fit audioState correctly. You can test the audioTime by watch the slideTime variable.

### CODE REVIEW

**Comment by WilliamParsons** [comment]
seems good to me 👍

**Comment by WilliamParsons** [comment]
just need to resolve the merge conflicts

**Comment by jink-e** [comment]
I suggest to add rule to .gitignore to ignore all those .class files under /bin

**Comment by WilliamParsons** [comment]
yeah if you update it with those changes then it should be fine with me

**Pull request merged**
